### PR TITLE
On demand azure gcp

### PR DESCRIPTION
**Pull request by dbbnicole**
Adding on-demand configurations for Azure and GCP.

### CODE REVIEW

**Review by simonfl-db — COMMENTED** [review]
This PR also does the conversion to use the python SDK, was that intended?

**Comment by simonfl-db** [comment]
I'd love to run this on each of the clouds and make sure it works before merging it in

**Comment by bchiang2** [comment]
Agree with @simonfl-db, I think we should test this script before merging.

**Comment by simonfl-db** [comment]
I'll spin up some testshard instances and test it out

**Review by bchiang2 — COMMENTED** [review]
For some reason I can't comment on the file.
Here are some nit

1. could we rename `w = WorkspaceClient()` to `workspace_client = WorkspaceClient()`
2. rename `all = w.clusters.list()` to `cluster_list = workspace_client.clusters.list()` (all is a reserved Python built-in function https://docs.python.org/3/library/functions.html
3. the last error is not raised ```else: 
    ValueError(
        f"The Databricks git proxy server only supports AWS, Azure and GCP. Running on an unsupported cloud. Please contact support."
    )```

**Comment by dbbnicole** [comment]
@bchiang2 Thanks for the comments!
1. w = WorkspaceClient() is the standard naming for python SDK usage. We should keep it consistent.
2 and 3. Can you please make the edits directly in a commit?

**Comment by dbbnicole** [comment]
I added a commit that included a notice and a commented code block for people to revert the config if they are only testing. See context: https://databricks.slack.com/archives/C05TL8Z7687/p1696397487206309

**Comment by simonfl-db** [comment]
# Manual testing
✅ 

# Create cluster POST request data: 
## GCP

```json
{'cluster_name': 'Repos Git Proxy', 'spark_version': '12.2.x-scala2.12', 'autotermination_minutes': 0, 'num_workers': 0, 'spark_conf': {'spark.databricks.cluster.profile': 'singleNode', 'spark.master': 'local[*]'}, 'custom_tags': {'ResourceClass': 'SingleNode'}, 'gcp_attributes': GcpAttributes(availability=None, boot_disk_size=None, google_service_account=None, local_ssd_count=None), 'node_type_id': 'e2-standard-4'}
```
`Command took 8.29 minutes`

## AWS
Create cluster POST request data: 
```json
{'cluster_name': 'Repos Git Proxy', 'spark_version': '12.2.x-scala2.12', 'autotermination_minutes': 0, 'num_workers': 0, 'spark_conf': {'spark.databricks.cluster.profile': 'singleNode', 'spark.master': 'local[*]'}, 'custom_tags': {'ResourceClass': 'SingleNode'}, 'aws_attributes': AwsAttributes(availability=None, ebs_volume_count='1', ebs_volume_iops=None, ebs_volume_size='32', ebs_volume_throughput=None, ebs_volume_type=None, first_on_demand='1', instance_profile_arn=None, spot_bid_price_percent=None, zone_id=None), 'node_type_id': 'm5.large'}
```
`Command took 5.92 minute`

## Azure
Create cluster POST request data: 
```json
{'cluster_name': 'Repos Git Proxy', 'spark_version': '12.2.x-scala2.12', 'autotermination_minutes': 0, 'num_workers': 0, 'spark_conf': {'spark.databricks.cluster.profile': 'singleNode', 'spark.master': 'local[*]'}, 'custom_tags': {'ResourceClass': 'SingleNode'}, 'azure_attributes': AzureAttributes(availability=<AzureAvailability.ON_DEMAND_AZURE: 'ON_DEMAND_AZURE'>, first_on_demand=None, log_analytics_info=None, spot_bid_max_price=None), 'node_type_id': 'Standard_DS3_v2'}
```
`Command took 4.05 minutes`

# Testing git functionality
I checked out this repo (https://github.com/databricks/databricks-repos-proxy) on all 3 clouds and it worked successfully.

From the checked out repo I ran the `debug_git_proxy_jupyter` notebook, using `https://github.com/databricks/databricks-repos-proxy` as the git repo url

**Review by bchiang2 — APPROVED** [review]

**Review by simonfl-db — APPROVED** [review]

**Pull request merged**
